### PR TITLE
contributte docs style

### LINKED ISSUE #73: Contributte style docs folder

### PR DESCRIPTION
**Pull request by artemevsin**
closes #73 
not sure where examples folder should belong, so I put it into .docs folder

### CODE REVIEW

**Comment by f3l1x** [comment]
Hey, thanks, I would remove docs for v2.x from .docs/readme.md and refer to whole v2.x docs to here https://github.com/contributte/gopay/tree/v2.3.x.

**Comment by f3l1x** [comment]
Ping

**Comment by artemevsin** [comment]
I deleted everything related to v2.x except one link in main README.md file. Also fixed link to example presenter

**Comment by f3l1x** [comment]
👍

**Pull request merged**
